=== usnistgov/metaschema/test-suite/schema-generation/char-handling/charstrings-test_xml-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:m="http://csrc.nist.gov/ns/oscal/metaschema/1.0"
           xmlns:metaschema-datatypes-dateTime="http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-dateTime"
           xmlns:oscal-prose="http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-dateTime"
           elementFormDefault="qualified"
           targetNamespace="http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-dateTime"
           version="1.0-milestone1">
   <xs:annotation>
      <xs:appinfo>
         <m:schema-name>Metaschema Unit Test: datatypes-dateTime</m:schema-name>
         <m:schema-version>1.0-milestone1</m:schema-version>
         <m:short-name>metaschema-datatypes-dateTime</m:short-name>
         <m:root>examples</m:root>
      </xs:appinfo>
   </xs:annotation>
   <xs:element name="examples" m:root="yes">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Examples</m:formal-name>
            <m:description>Some character strings of different sorts</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Examples</b>: Some character strings of different sorts</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="metaschema-datatypes-dateTime:charstring"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
            <xs:element ref="metaschema-datatypes-dateTime:markupline"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="charstring">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Character string</m:formal-name>
            <m:description>String of characters</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Character string</b>: String of characters</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string"/>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="markupline">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Markup line</m:formal-name>
            <m:description>Characters, and more</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Markup line</b>: Characters, and more</xs:documentation>
      </xs:annotation>
      <xs:complexType mixed="true">
         <xs:group ref="metaschema-datatypes-dateTime:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h1">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h2">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h3">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h4">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h5">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="h6">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:inlines"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="p">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="pre">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="ol">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:li"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="li">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:everything-inline"/>
            <xs:element ref="oscal-prose:ol"/>
            <xs:element ref="oscal-prose:ul"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="ul">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:li"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="table">
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:tr"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="tr">
      <xs:complexType>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element maxOccurs="unbounded" ref="oscal-prose:td"/>
            <xs:element maxOccurs="unbounded" ref="oscal-prose:th"/>
         </xs:choice>
      </xs:complexType>
   </xs:element>
   <xs:element name="th">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="td">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:everything-inline"/>
      </xs:complexType>
   </xs:element>
   <xs:group name="everything-inline">
      <xs:sequence>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:group ref="oscal-prose:special"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
      </xs:sequence>
   </xs:group>
   <xs:group name="mix">
      <xs:sequence>
         <xs:group minOccurs="0" maxOccurs="unbounded" ref="oscal-prose:inlines"/>
      </xs:sequence>
   </xs:group>
   <xs:group name="inlines">
      <xs:sequence>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:q"/>
            <xs:element ref="oscal-prose:code"/>
            <xs:element ref="oscal-prose:em"/>
            <xs:element ref="oscal-prose:i"/>
            <xs:element ref="oscal-prose:strong"/>
            <xs:element ref="oscal-prose:b"/>
            <xs:element ref="oscal-prose:sub"/>
            <xs:element ref="oscal-prose:sup"/>
            <xs:element ref="oscal-prose:img"/>
         </xs:choice>
      </xs:sequence>
   </xs:group>
   <xs:element name="q">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:code"/>
            <xs:element ref="oscal-prose:em"/>
            <xs:element ref="oscal-prose:i"/>
            <xs:element ref="oscal-prose:b"/>
            <xs:element ref="oscal-prose:strong"/>
            <xs:element ref="oscal-prose:sub"/>
            <xs:element ref="oscal-prose:sup"/>
         </xs:choice>
      </xs:complexType>
   </xs:element>
   <xs:element name="code">
      <xs:complexType mixed="true">
         <xs:group ref="oscal-prose:mix"/>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="strong">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="em">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="i">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="b">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="oscal-prose:mix"/>
            <xs:element ref="oscal-prose:a"/>
         </xs:choice>
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="sub">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="sup">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="oscal-prose:optionalClass"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="img">
      <xs:complexType>
         <xs:attribute name="alt"/>
         <xs:attribute name="src" use="required" type="xs:anyURI"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="a">
      <xs:complexType mixed="true">
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:q"/>
            <xs:element ref="oscal-prose:code"/>
            <xs:element name="em">
               <xs:complexType mixed="true">
                  <xs:attributeGroup ref="oscal-prose:optionalClass"/>
               </xs:complexType>
            </xs:element>
         </xs:choice>
         <xs:attribute name="href"/>
      </xs:complexType>
   </xs:element>
   <xs:group name="special">
      <xs:sequence>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="oscal-prose:insert"/>
         </xs:choice>
      </xs:sequence>
   </xs:group>
   <xs:element name="insert">
      <xs:complexType>
         <xs:attribute name="param-id" use="required" type="xs:NCName"/>
      </xs:complexType>
   </xs:element>
   <xs:attributeGroup name="requiredClass"/>
   <xs:attributeGroup name="optionalClass"/>
   <xs:attributeGroup name="hrefAttr">
      <xs:attribute name="href"/>
   </xs:attributeGroup>
</xs:schema>

=== usnistgov/metaschema/test-suite/schema-generation/datatypes/charstrings_test_okay_PASS.xml
<?xml version="1.0" encoding="UTF-8"?>
<examples xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-dateTime charstrings-test_xml-schema.xsd"
 xmlns="http://csrc.nist.gov/ns/metaschema/unit-test/datatypes-dateTime">
  <charstring>Here's a string including punctuation ' " \ . $</charstring>
  <charstring>Here's a string with an ampersand &amp;</charstring>
  <charstring>Less-than and greater-than, as &lt;delimiters> ...</charstring>
  <charstring>The star aka asterisk * may be magical and maybe also the tick `</charstring>
  <markupline>Also, occasionally we have <a href="w3.org">links</a> and <em>other markup</em>.</markupline>
  <markupline>And <em>sometimes</em>, we have *very confusing stuff* as well.</markupline>
</examples>
